### ISSUE TITLE
is finetuning avaliable?

### ISSUE THREAD

**Issue by robchenchen** [M-Nauta/ProtoTree#10]
Hi, thanks for this awesome paper, I was just wondering if finetuning neuro prototree is possible?

**Comment by M-Nauta** [comment]
Do you mean that you train ProtoTree on one dataset, and then finetune it on a related but different dataset? We haven't tried this ourselves but it might be possible by saving the model, and then loading and training further on another dataset. Feel free to try! However, when the class labels between the datasets differ, I would recommend to at least re-initialize the leaves of ProtoTree, since a different classification task will require different class distributions in the leaves. 

Also, we have recently published a new part-prototype model: [PIP-Net](https://github.com/M-Nauta/PIPNet). That might be of interest to you as well :)
