### ISSUE TITLE
Projection of prototypes

### ISSUE THREAD

**Issue by EoinKenny** [M-Nauta/ProtoTree#5]
Hi thanks for the great repo, it was really easy to reproduce.

I've just a general question about the projection step, you seem to use the bounding boxes to do projection right? Like you crop the images to just the box around each bird as the data for the loader used for projection.

Why is that? Does it not work as well with the full images? Or is there a technical reason? Thanks in advance.

**Comment by M-Nauta** [comment]
Thanks.
The reason is to improve the interpretability of the model. Without bounding boxes, a bird in this dataset might be quite small in the image and the whole (or most of the) bird might end up in one single patch. To visually distinguish between prototypical parts in a bird and hence improve the interpretability, we therefore projected the latent prototypes onto cropped images. Note that this is only done for the projection step, since bounding boxes are not needed for testing and using the model.
